version: "3"

tasks:
    add:wasm32-wasi:target: rustup target add wasm32-wasi
    build:
        deps:
            - add:wasm32-wasi:target
            - build-shims
        cmds:
            - cargo build --target wasm32-wasi --release
            - cp ./target/wasm32-wasi/release/wasmjs-engine.wasm ./
    build-shims:
        deps:
            - shims-install
        dir: shims
        cmds:
            - echo pwd
            - npm run build
    shims-install:
        dir: shims
        cmds:
            - pwd
            - npm install
