import {
  Qdrant,
  QdrantHttpClient,
  QdrantHttpRequest,
} from "@arakoodev/edgechains.js/vector-db";

const requests: unknown[] = [];
const mockHttpClient: QdrantHttpClient = {
  async request<T = unknown>(config: QdrantHttpRequest) {
    requests.push(config);
    return {
      data: {
        result: {
          ok: true,
          url: config.url,
        },
      } as T,
    };
  },
};

const qdrant = new Qdrant("http://localhost:6333", "demo-key", {
  httpClient: mockHttpClient,
});
const client = qdrant.createClient();

await qdrant.createCollection({
  client,
  collectionName: "edgechains_docs",
  vectorSize: 3,
});
await qdrant.insertVectorData({
  client,
  tableName: "edgechains_docs",
  id: "doc-1",
  embedding: [0.1, 0.2, 0.3],
  content: "Qdrant stores vectors and payloads for semantic search.",
  payload: {
    source: "example",
  },
});
await qdrant.getDataFromQuery({
  client,
  tableName: "edgechains_docs",
  embedding: [0.1, 0.2, 0.3],
  limit: 3,
});

console.log("Qdrant REST requests generated by the example:");
console.log(JSON.stringify(requests, null, 2));
