name: PR Build

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    outputs:
      VALUE: ${{ steps.short_hash.outputs.VALUE }}
    steps:
      - name: Checkout PR
        if: ${{ github.event_name == 'pull_request_target' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set SHORT_HASH
        run: |
          echo "::set-output name=VALUE::${LONG_HASH:0:8}"
          echo "RELEASE_TAG=${LONG_HASH:0:8}-$(TZ=UTC-8 date +"%Y.%m.%d")" >> $GITHUB_ENV
        id: short_hash
        env:
          LONG_HASH: ${{ github.sha }}

      - name: Determine changed directories
        id: changed_dirs
        run: |
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(Java|JS)/' | cut -d/ -f1 | sort -u)
          echo "CHANGED_DIRS=${CHANGED_DIRS}" >> $GITHUB_ENV
        shell: bash

      - name: Set up JDK and Node.js
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Build Java code
        if: ${{ contains(env.CHANGED_DIRS, 'Java') }}
        working-directory: ./FlySpring
        run: mvn clean package -DskipTests

      - name: Build JavaScript code
        if: ${{ contains(env.CHANGED_DIRS, 'JS') }}
        run: |
          npm install
          npm run build

      - name: Create output folder
        run: mkdir BuildOutput

      - name: Copy JAR to Output folder
        if: ${{ contains(env.CHANGED_DIRS, 'Java') }}
        run: cp ./FlySpring/edgechain-app/target/edgechain.jar ./BuildOutput/

      - name: Copy JavaScript build to Output folder
        if: ${{ contains(env.CHANGED_DIRS, 'JS') }}
        run: cp -r ./JS/dist/* ./BuildOutput/

      - name: Upload Output folder as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Output
          path: ./BuildOutput/
